name:                webmention
version:             0.1.0.0
github:              "alexmingoia/webmention"
license:             BSD3
author:              "Alexander Mingoia"
maintainer:          "alex@alexmingoia.com"
copyright:           "2020 Alexander Mingoia"
synopsis:            Types and functions for working with Webmentions.
category:            "Web"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Types and functions for working with
             [Webmention](https://www.w3.org/TR/webmention), which pass the
             [webmention.rocks](https://webmention.rocks/) test suite.

dependencies:
- base >= 4 && < 5
- bytestring >= 0.10 && < 0.11
- case-insensitive >= 1.2 && < 1.3
- either >= 5.0 && < 5.1
- exceptions >= 0.10 && < 0.11
- hspec >= 2.7 && < 2.8
- http-types >= 0.12 && < 0.13
- http-client >= 0.6 && < 0.7
- http-client-tls >= 0.3 && < 0.4
- modern-uri >= 0.3 && < 0.4
- tagsoup >= 0.14 && < 0.15
- text >= 1.2 && < 1.3

library:
  source-dirs: src

tests:
  webmention-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webmention
